import { Topic, RecomendContent } from "./types";

export const topicListForRecomendation: Topic[] = [
  {
    id: 0,
    imagePath: "/news4_image.png",
    largeImagePath: "/news2_image_large.png",
    title: "【 AIに宿題をさせるべきか、させてはいけないのか 】",
    text: "夏休みの宿題にAIを使っている学生が増えているようだ。とある会社がじっしした調査によると、夏休みの宿題にAIを使用した小中高生は3人に1人。宿題に使った内容としては「作文」「数学」が上位にきていた。現在AIの使用にたいして、学校や親からの制限はまだ少ない。この状況を受け、AIに宿題をさせるべきか、それともさせてはいけないのか、今後考えていくべきと感じられる。",
    textShort:
      "夏休みの宿題を解くにAIを利用している学生が見られるが、AIに宿題をさせるべきか、させてはいけないのか？",
    contents: [
      {
        id: 0,
        text: "勉強のこうりつかは、忙しい時に大事。AIを使えば、短時間で高い学びの効果を実現できるぞ！",
        label: 0,
        userNameId: 0,
        userIconId: 0,
        likeCount: 1,
      },
      {
        id: 1,
        text: "AIを使って宿題を解くかていを見ることで、新しい考え方を学ぶことができますね〜",
        label: 0,
        userNameId: 1,
        userIconId: 1,
        likeCount: 1,
      },
      {
        id: 2,
        text: "宿題の目的は学びのほかん。そのしゅだんとして、AIのサポートを一部つかうのはかしこい。",
        label: 0,
        userNameId: 2,
        userIconId: 2,
        likeCount: 1,
      },
    ],
  },
];

export const contentsListForRecommendations: RecomendContent[] = [
  {
    id: 0,
    text: "宿題は勉強のためのものだよ！AIにやらせると、その目的がなくなっちゃうじゃん！！",
    type: "strongSupport",
    score: -4,
    skipScore: 2,
  },
  {
    id: 1,
    text: "AIに宿題をさせたらさ、自分の弱点や課題を知るきかいがへりますよね？",
    type: "strongSupport",
    score: -4,
    skipScore: 2,
  },
  {
    id: 2,
    text: "それじゃあ学びや考える力が育たないし…未来の学習能力をも低下させることにつながると思うんだが。",
    type: "strongSupport",
    score: -4,
    skipScore: 2,
  },
  {
    id: 3,
    text: "ほかに宿題やった学生にたいして不公平ですよね。自分でやったか、AIにやらせたかの違いは大きいです。",
    type: "strongSupport",
    score: -4,
    skipScore: 2,
  },

  {
    id: 4,
    text: "たまに答えをチェックするためにAIを使うのはいいかもしれないが、全部AIにやらせるのは良くないかな〜",
    type: "weakSupport",
    score: -2,
    skipScore: 4,
  },
  {
    id: 5,
    text: "自分で考えることが大事です！全部AIにいぞんしちゃうと、その力が育たないです！",
    type: "weakSupport",
    score: -2,
    skipScore: 4,
  },
  {
    id: 6,
    text: "宿題は、授業で自分がどれくらい理解したかわかるしゅだん。AIにたよりすぎると、自分のひょうかができないよ？",
    type: "weakSupport",
    score: -2,
    skipScore: 4,
  },
  {
    id: 7,
    text: "AIに宿題やらせてたら、自分自身の学びのしつが下がりませんかね。",
    type: "weakSupport",
    score: -2,
    skipScore: 4,
  },
  {
    id: 8,
    text: "AIをりようして宿題の解説をうけるのはいい学びになるけどな〜",
    type: "weakObjection",
    score: 4,
    skipScore: -2,
  },
  {
    id: 9,
    text: "難しすぎて手をつけられない宿題に対して、AIのサポートを受けるのは勉強になると思いますが。",
    type: "weakObjection",
    score: 4,
    skipScore: -2,
  },
  {
    id: 10,
    text: "テクノロジーを活用してより新たな学び方をもさくするのは、21世紀のスキルとして必要かと。",
    type: "weakObjection",
    score: 4,
    skipScore: -2,
  },
  {
    id: 11,
    text: "AIに部分的にたよることで、勉強にたいする興味を強化できる面もあるかもしれません。",
    type: "weakObjection",
    score: 4,
    skipScore: -2,
  },
  {
    id: 12,
    text: "時間がない時に一部をAIにやらせて、一部自分でやることでバランス取れると思います。",
    type: "strongObjection",
    score: 2,
    skipScore: -4,
  },
  {
    id: 13,
    text: "難しい宿題では、AIが解きながら例をだしてくれることで、学生の理解が深まる。",
    type: "strongObjection",
    score: 2,
    skipScore: -4,
  },
  {
    id: 14,
    text: "これからの時代は、AIを上手く使うことで、必要な知識やスキルをこうりつよく学ぶべき！",
    type: "strongObjection",
    score: 2,
    skipScore: -4,
  },
  {
    id: 15,
    text: "自分でやるか、AIにやらせるかをみきわめる能力は新時代にひつよう！その能力を育てる上でAIの利用はおすすめするべき！",
    type: "strongObjection",
    score: 2,
    skipScore: -4,
  },
];
