import { Name } from "./types";

export const userNames: Name[] = [
  { name: "さとうしお", englishName: "Suger-shio" },
  { name: "おむすび", englishName: "omusubi" },
  { name: "てんどんマン", englishName: "Tendon-man" },
  { name: "ユーゴくん", englishName: "YUGO" },
  { name: "あずき", englishName: "Azuki" },
  { name: "千羽鶴", englishName: "turu" },
  { name: "テクテク", englishName: "tektek" },
  { name: "ブラック", englishName: "black" },
  { name: "そら", englishName: "SORA" },
  { name: "あくあ", englishName: "aqua" },
  { name: "レッド", englishName: "red" },
  { name: "ざくろ", englishName: "ZAKURO" },
  { name: "坦々麺", englishName: "tantanmen" },
  { name: "ジンジャー", englishName: "ginger" },
  { name: "安藤", englishName: "ANDO" },
  { name: "タケシさん", englishName: "Takeshi" },
  { name: "滝沢", englishName: "Takizawa" },
  { name: "ピカモン", englishName: "Pika-mon" },
  { name: "東京大学 田中先生", englishName: "Tokyo Univ. TANAKA" },
  { name: "ひがし動物園 小林園長", englishName: "EAST ZOO Kobayashi" },
  { name: "みそしょうゆ", englishName: "Miso-oil" },
  { name: "てんぷら", englishName: "Tempra" },
  { name: "おやこどんマン", englishName: "Oyakodon-man" },
  { name: "ソウジくん", englishName: "SOUJI" },
  { name: "だいず", englishName: "Daizu" },
  { name: "元気玉", englishName: "Genkidama" },
  { name: "ボコボコ", englishName: "Bokoboko" },
  { name: "ホワイト", englishName: "White" },
  { name: "だいち", englishName: "DAICHI" },
  { name: "るびい", englishName: "Ruby" },
  { name: "ブルー", englishName: "Blue" },
  { name: "いちじく", englishName: "FIGS" },
  { name: "棒棒鶏", englishName: "Banbanji" },
  { name: "オニオン", englishName: "Onion" },
  { name: "高橋", englishName: "TAKAHASHI" },
  { name: "サトシさん", englishName: "Satoshi" },
  { name: "清水", englishName: "Shimizu" },
  { name: "チュウモン", englishName: "Chumon" },
  { name: "東京大学 正野先生", englishName: "Tokyo Univ. MASANO" },
  { name: "生物研究者 大山さん", englishName: "Biologist Oyama" },
  { name: "東京大学 田中義雄", englishName: "Tokyo Univ. TANAKA" },
  { name: "中東政治専門家 小林博", englishName: "" },
  { name: "東京大学 正野和彦", englishName: "Tokyo Univ. MASANO" },
  { name: "中東問題研究者 大山大輔", englishName: "" },
];
