export const userIcons = [
  "/userIcons/Profile_1.png",
  "/userIcons/Profile_2.png",
  "/userIcons/Profile_3.png",
  "/userIcons/Profile_4.png",
  "/userIcons/Profile_5.png",
  "/userIcons/Profile_6.png",
  "/userIcons/Profile_7.png",
  "/userIcons/Profile_8.png",
  "/userIcons/Profile_9.png",
  "/userIcons/Profile_10.png",
  "/userIcons/Profile_11.png",
  "/userIcons/Profile_12.png",
  "/userIcons/Profile_13.png",
  "/userIcons/Profile_14.png",
  "/userIcons/Profile_15.png",
];
